version: '3.8'

services:
  api:
    build:
      context: ./api
    container_name: myapi
    ports:
      - "8000:8000"

  ui:
    build:
      context: ./ui
    container_name: myui
    ports:
      - "8501:8501"
    depends_on:
      - api

networks:
  ml-project-network:
    driver: bridge
